language: python
before_install:
  - echo "running before_install ..."
  - echo $TRAVIS_COMMIT_MESSAGE
  - "echo $TRAVIS_COMMIT_MESSAGE"
before_script:
  - echo "running before_script ..."
  - echo $TRAVIS_COMMIT_MESSAGE
  - "echo $TRAVIS_COMMIT_MESSAGE"
after_script:
  - echo "running after_script ..."
  - echo $TRAVIS_COMMIT_MESSAGE
  - "echo $TRAVIS_COMMIT_MESSAGE"
after_success:
  - echo "running after_success ..."
  - echo $TRAVIS_COMMIT_MESSAGE
  - "echo $TRAVIS_COMMIT_MESSAGE"
after_failure:
  - echo "running after_failure ..."
  - echo $TRAVIS_COMMIT_MESSAGE
  - "echo $TRAVIS_COMMIT_MESSAGE"
script: echo $TRAVIS_COMMIT_MESSAGE; cat $TRAVIS_HOME/.travis/job_stages
install: if [[ $TRAVIS_COMMIT_MESSAGE == "hello" ]];
  ls
fi
