name: Run scorecard-action
on:
  pull_request_target:
    branches: [ main ]

permissions: write-all

jobs:
    scorecard:
      runs-on: ubuntu-latest
      permissions:
        security-events: write
      steps:
        - uses: raghavkaul/scorecard-action@HEAD
          with:
            results_file: results.sarif
            results_format: sarif
            # publish_results: true
