name: Run scorecard-action
on:
  pull_request:
    branches: [ main ]

jobs:
    scorecard:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        security-events: write
        statuses: write
      steps:
        - uses: raghavkaul/scorecard-action@HEAD
          with:
            results_file: results.sarif
            results_format: sarif
            # publish_results: true
